update version and remove unused var
To resolve error below"

Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider
hashicorp/azurerm: no available releases match the given constraints ~>
2.55.0, ~> 2.81.0